{
    'name': 'cantrat',
    'version': '15.0.1.0.0',
    'summary': """Manage the company properties when it is in the custody of an employee""",
    'description': 'Manage the company properties when it is in the custody of an employee',
    'live_test_url': 'https://youtu.be/rd62HYzZxFI',
    'category': 'Generic Modules/Human Resources',
    'author': 'Cybrosys Techno solutions,Open HRMS',
    'company': 'Cybrosys Techno Solutions',
    'maintainer': 'Cybrosys Techno Solutions',
    'website': "https://www.openhrms.com",
    'depends': ['hr', 'hr_contract', 'hr_employee_updation', 'hr_contract_types'],
    'data': [
        'security/ir.model.access.csv',
        'data/data_type_contra.xml',
    ],
    'license': 'AGPL-3',
    'installable': True,
    'auto_install': False,
    'application': False,
}
